// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"

	// EdgeDrugs holds the string denoting the drugs edge name in mutations.
	EdgeDrugs = "drugs"

	// Table holds the table name of the user in the database.
	Table = "users"
	// DrugsTable is the table the holds the drugs relation/edge.
	DrugsTable = "drugs"
	// DrugsInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugsInverseTable = "drugs"
	// DrugsColumn is the table column denoting the drugs relation/edge.
	DrugsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldEmail,
	FieldPassword,
}

var (
	// UsernameValidator is a validator for the "Username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// EmailValidator is a validator for the "Email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "Password" field. It is called by the builders before save.
	PasswordValidator func(string) error
)
