// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Drug is the predicate function for drug builders.
type Drug func(*sql.Selector)

// Form is the predicate function for form builders.
type Form func(*sql.Selector)

// Unit is the predicate function for unit builders.
type Unit func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Volume is the predicate function for volume builders.
type Volume func(*sql.Selector)
