/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntUnitEdges,
    EntUnitEdgesFromJSON,
    EntUnitEdgesFromJSONTyped,
    EntUnitEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUnit
 */
export interface EntUnit {
    /**
     * UnitType holds the value of the "UnitType" field.
     * @type {string}
     * @memberof EntUnit
     */
    unitType?: string;
    /**
     * 
     * @type {EntUnitEdges}
     * @memberof EntUnit
     */
    edges?: EntUnitEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntUnit
     */
    id?: number;
}

export function EntUnitFromJSON(json: any): EntUnit {
    return EntUnitFromJSONTyped(json, false);
}

export function EntUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUnit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'unitType': !exists(json, 'UnitType') ? undefined : json['UnitType'],
        'edges': !exists(json, 'edges') ? undefined : EntUnitEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntUnitToJSON(value?: EntUnit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'UnitType': value.unitType,
        'edges': EntUnitEdgesToJSON(value.edges),
        'id': value.id,
    };
}


