/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntVolumeEdges,
    EntVolumeEdgesFromJSON,
    EntVolumeEdgesFromJSONTyped,
    EntVolumeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntVolume
 */
export interface EntVolume {
    /**
     * VolumeType holds the value of the "VolumeType" field.
     * @type {string}
     * @memberof EntVolume
     */
    volumeType?: string;
    /**
     * 
     * @type {EntVolumeEdges}
     * @memberof EntVolume
     */
    edges?: EntVolumeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntVolume
     */
    id?: number;
}

export function EntVolumeFromJSON(json: any): EntVolume {
    return EntVolumeFromJSONTyped(json, false);
}

export function EntVolumeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntVolume {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'volumeType': !exists(json, 'VolumeType') ? undefined : json['VolumeType'],
        'edges': !exists(json, 'edges') ? undefined : EntVolumeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntVolumeToJSON(value?: EntVolume | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'VolumeType': value.volumeType,
        'edges': EntVolumeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


